import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import QueryContainer from "@/components/QueryProvider";

const space_Mono = Space_Mono({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={space_Mono.className}>
        <ThemeProvider attribute="class">
          <QueryContainer>{children}</QueryContainer>
        </ThemeProvider>
      </body>
    </html>
  );
}
